require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.keymaps"
require "user.nvim-tree"
require "user.telescope"
require "user.impatient"
require "user.lualine"
-- require "user.bufferline"
require "user.treesitter"

vim.cmd "source ~/.config/nvim/coc/config.vim"
